### ISSUE TITLE
Loving the theme, have a couple of requests...

### ISSUE THREAD

**Issue by teejayen** [mmarfil/marfa#4]
Loving the theme, it's so simple and clean. I've made a couple of customisations and was hoping you may be able to assist with a couple of requests.

- Is there any easy way to change the code syntax highlighting used? I post a few PowerShell examples and it would be very helpful.

- I've tried ordering instructions into a numbered list, but can't get the numbers to show.

**Comment by mmarfil** [comment]
Hey @teejayen, thanks for using the theme. Before anything, let me start by saying that I suspect my answers below won't be too helpful, I'm only a designer and my code skills are not that great.

> Is there any easy way to change the code syntax highlighting used? I post a few PowerShell examples and it would be very helpful.

I think you'll need to go through Jekyll's [documentation](https://jekyllrb.com/docs/home/) and implement the desired code highlighting. It's not something I did before, but I imagine you'll need to edit `highlight.css` and also add a setting to `_config.yml`?

> I've tried ordering instructions into a numbered list, but can't get the numbers to show.

Right now, all lists type are set to `circle`. I'm not sure how to support both normal + numbered lists via CSS. So, a workaround would be to first remove all `list-style-type` references, and then hardcode the style-type in the post itself.

Again, sorry for the no-help response… if you find better ways to do this, I'd be happy to update the theme to support both of your requests.

**Comment by teejayen** [comment]
For the interim, I've swapped to using another theme (Poole). I will have a look into this down the track and submit a pull request if I can sort it out.
